### ISSUE TITLE
Crash on Django migrate (python3 manage.py migrate)

### ISSUE THREAD

**Issue by goldeye-xor** [r4fek/django-scylla#63]
This error appeared on a Django project created at the moment, without an additional model

```
PS C:\Users\r.cretin\Desktop\odurance-ng\odurance> py .\manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "C:\Users\r.cretin\Desktop\odurance-ng\odurance\manage.py", line 22, in <module>
    main()
  File "C:\Users\r.cretin\Desktop\odurance-ng\odurance\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\commands\migrate.py", line 376, in handle
    emit_post_migrate_signal(
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\sql.py", line 52, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\management\__init__.py", line 83, in create_permissions
    ctypes.add(ctype)
  File "C:\Users\r.cretin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 603, in __hash__
    raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable
```

Config:
```
DATABASES = {
     'default': {
         'ENGINE': 'django_scylla',
         'NAME': 'odurance',
         'HOST': '10.1.10.9',
     }
 }
 ```

**Comment by NoiSek** [comment]
This has taken some time to address, but I'm fairly certain I understand _where_ that error is coming from. What I don't understand is _why_ you're seeing this error.

If I'm understanding your issue properly you see this error when you migrate an app with no models defined, but that is strange given our demo setup itself also has no models.

If you still have this environment available, can you provide context on what your setup and dependency versions are?

**Comment by lukadisanto** [comment]
Hi, 
I start a simple django project (django-admin startproject project_name), then I copy your DATABASE config but migration got an exception.

I use Django 5 with python 3.12

```✖  python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/delivero/manage.py", line 22, in <module>
    main()
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/delivero/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 143, in migrate
    self.check_replacements()
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 301, in check_replacements
    applied = self.recorder.applied_migrations()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 82, in applied_migrations
    return {
           ^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django_scylla/cql/compiler.py", line 57, in as_sql
    self.compile(self.where) if self.where is not None else ("", [])
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 544, in compile
    sql, params = vendor_impl(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django_scylla/cql/where.py", line 6, in as_scylladb
    res, params = super().as_sql(compiler, connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucadisanto/Projects/Wide/Delivero/backend/venv/lib/python3.12/site-packages/django/db/models/sql/where.py", line 174, in as_sql
    raise FullResultSet
django.core.exceptions.FullResultSet
```

**Comment by targetfff** [comment]
> Hi, I start a simple django project (django-admin startproject project_name), then I copy your DATABASE config but migration got an exception.
> 
> I use Django 5 with python 3.12

I'm having the same issue now, did you solve it?
