### ISSUE TITLE
OperationalError while migrating (syntax error near ""django_content_type"")

### ISSUE THREAD

**Issue by MatteoFasulo** [r4fek/django-scylla#64]
While running python3 manage.py migrate this is the output:

```
(.venv) @MatteoFasulo ➜ /workspaces/Django-Cassandra-Social-Network (main) $ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, blog, chat, contenttypes, sessions, social_django, users
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying auth.0013_alter_user_email... OK
  Applying blog.0001_initial... OK
  Applying blog.0002_post_post_counter_post_likes_post_likes_by_time_and_more... OK
  Applying blog.0003_message_alter_timeline_options... OK
  Applying blog.0004_delete_message... OK
  Applying blog.0005_post_comment... OK
  Applying blog.0006_alter_post_options_alter_post_comment_options_and_more... OK
  Applying chat.0001_initial... OK
  Applying chat.0002_chat... OK
  Applying chat.0003_alter_chat_options_alter_message_options... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying social_django.0009_auto_20191118_0520... OK
  Applying social_django.0010_uid_db_index... OK
  Applying social_django.0011_alter_id_fields... OK
  Applying users.0001_initial... OK
  Applying users.0002_alter_profile_options... OK
  Applying users.0003_followers_following... OK
  Applying users.0004_alter_followers_options_alter_following_options_and_more... OK
Traceback (most recent call last):
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: near ""django_content_type"": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/Django-Cassandra-Social-Network/manage.py", line 22, in <module>
    main()
  File "/workspaces/Django-Cassandra-Social-Network/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 383, in handle
    emit_post_migrate_signal(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/contrib/auth/management/__init__.py", line 90, in create_permissions
    all_perms = set(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 246, in __iter__
    return compiler.results_iter(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1513, in results_iter
    results = self.execute_sql(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/workspaces/Django-Cassandra-Social-Network/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: near ""django_content_type"": syntax error
```

DB config in settings.py:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },

    'scylla': {
        'ENGINE': 'django_scylla',
        'HOST': 'scylla',
        "PORT": 9042,
        'NAME': 'mysocial',
        'TEST_NAME': 'test_mysocial',
        "OPTIONS": {
            "replication": {
                "class": "SimpleStrategy",
                "replication_factor": 1
            },
            "connection": {
                "consistency_level": ConsistencyLevel.ONE
            },
            "execution_profile": {
                "request_timeout": 5,
            }
        },
    },
}
```

Do you know where this `syntax error near ""django_content_type"":` comes from?

**Comment by MatteoFasulo** [comment]
EDIT: I think it could be related to the column type in models.py, does `django-scylla` support the `Counter` column type?

**Comment by v-spassky** [comment]
Experiencing the same issue with PostgreSQL:

```
psycopg2.errors.SyntaxError: syntax error at or near ""django_content_type""
```

@MatteoFasulo, did you manage to resolve this somehow by any chance?

**Comment by MatteoFasulo** [comment]
> Experiencing the same issue with PostgreSQL:
> 
> ```
> psycopg2.errors.SyntaxError: syntax error at or near ""django_content_type""
> ```
> 
> @MatteoFasulo, did you manage to resolve this somehow by any chance?

Hi,
yes I fixed the issue but I did not use the `django-scylla` library. I used `scylla-driver` with `django-cassandra-engine` from @r4fek supporting my previous DB structure made with Cassandra (I shifted to ScyllaDB coming from Cassandra environment)
